extends SceneTree
const Platform = preload("res://scripts/battle/battle_ui/model_platform.gd")
func _init() -> void:
	assert(Platform.allows(false, false, false, false, false))
	assert(not Platform.allows(false, true, true, false, true), "Regular Android remains 2D")
	assert(not Platform.allows(false, true, true, true, false), "Release Android cannot enable the debug pilot")
	assert(not Platform.allows(true, true, true, true, true), "Web remains sprite-only")
	assert(not Platform.allows(false, true, false, true, true), "Other mobile platforms remain disabled")
	assert(Platform.allows(false, true, true, true, true))
	assert(Platform.allows(false, true, true, false, false, true), "Experimental Android release supports models")
	assert(not Platform.allows(true, true, true, false, false, true), "Experimental tag cannot enable browser models")
	assert(not Platform.allows(false, true, false, false, false, true), "Experimental tag cannot enable other mobile platforms")
	assert(Platform.render_dimensions(Vector2i(2000,1200), false) == Vector2i(2000,1200))
	assert(Platform.render_dimensions(Vector2i(2000,1200), true) == Vector2i(2000,1200), "Android keeps physical pixels rather than stretching 540p")
	assert(Platform.render_dimensions(Vector2i(2400,1080), true) == Vector2i(2400,1080), "Phone landscape retains its native aspect ratio")
	assert(Platform.render_dimensions(Vector2i(1080,2400), true) == Vector2i(1080,2400), "Portrait is not stretched into a landscape raster")
	assert(Platform.render_dimensions(Vector2i(0,1), true) == Vector2i(2,2))
	assert(Platform.render_dimensions(Vector2i(640,360), true) == Vector2i(640,360))
	var pool := preload("res://scripts/battle/arenas/shared/environment_pool.gd").new()
	var client := Node.new()
	root.add_child(pool)
	root.add_child(client)
	pool.borrower = weakref(client)
	pool.discard_when_unused()
	assert(not pool.is_queued_for_deletion(), "Changing to 2D retains the arena while a battle owns it")
	pool.release(client)
	assert(pool.is_queued_for_deletion(), "The finished 3D arena is discarded when returning to 2D")
	client.queue_free()
	print("ANDROID_3D_PLATFORM_OK ordinary_2d=true explicit_experiment=true")
	quit()
