extends SceneTree

func _init() -> void:
	_run.call_deferred()

func _run() -> void:
	var actor := Node3D.new()
	root.add_child(actor)
	var bone := Skeleton3D.new()
	bone.name = "Rig"
	actor.add_child(bone)
	bone.add_bone("Root")
	var player := AnimationPlayer.new()
	actor.add_child(player)
	var library := AnimationLibrary.new()
	player.add_animation_library("", library)
	var idle := Animation.new()
	idle.length = 1.0
	library.add_animation("idle", idle)
	var attack := Animation.new()
	attack.length = 2.0
	var track := attack.add_track(Animation.TYPE_SCALE_3D)
	attack.track_set_path(track, NodePath("Rig:Root"))
	attack.track_insert_key(track, 0.0, Vector3.ONE)
	attack.track_insert_key(track, 2.0, Vector3(4, 5, 6))
	library.add_animation("attack", attack)
	var helper := preload("res://tools/sprite_factory/complete_pose_channels.gd").new()
	assert(helper.apply(actor) and helper.inserted == 1)
	assert(attack.track_get_key_count(track) == 2)
	assert(attack.track_get_key_time(track, 1) == 2.0)
	assert(attack.track_get_key_value(track, 1) == Vector3(4, 5, 6))
	player.play("attack")
	player.seek(2.0, true)
	assert(bone.get_bone_pose_scale(0).is_equal_approx(Vector3(4, 5, 6)))
	player.play("idle")
	player.seek(0.5, true)
	assert(bone.get_bone_pose_scale(0).is_equal_approx(Vector3.ONE))
	var again := preload("res://tools/sprite_factory/complete_pose_channels.gd").new()
	assert(again.apply(actor) and again.inserted == 0)
	var invalid := attack.add_track(Animation.TYPE_POSITION_3D)
	attack.track_set_path(invalid, NodePath("Rig:MissingBone"))
	attack.track_insert_key(invalid, 0.0, Vector3.ZERO)
	var before := idle.get_track_count()
	var reject := preload("res://tools/sprite_factory/complete_pose_channels.gd").new()
	assert(not reject.apply(actor) and "Unknown native bone" in reject.failure)
	assert(idle.get_track_count() == before)
	actor.free()
	print("PASS: omitted channels restore idle, native keys preserved, idempotent, invalid binding rejected")
	quit()
