extends SceneTree

const SERVICE_PATH := "res://scripts/services/guild_service.gd"
const PROJECT_PATH := "res://project.godot"

var failed := false


func _init() -> void:
	var service_source := FileAccess.get_file_as_string(SERVICE_PATH)
	var project_source := FileAccess.get_file_as_string(PROJECT_PATH)

	_check_contains(service_source, 'GUILDS_ENDPOINT := "/game/guilds"', "guild service uses the gateway guild endpoint")
	_check_contains(service_source, '"requestId": pending_creation_request_id', "guild creation has an idempotency key")
	_check_contains(service_source, "func load_directory", "guild service loads authoritative directory state")
	_check_contains(service_source, "func load_invitations", "guild service loads incoming invitations independently")
	_check_contains(service_source, 'GUILD_INVITATIONS_ENDPOINT := "/game/guild-invitations"', "guild invitation polling avoids loading the directory")
	_check_contains(service_source, "func create_guild", "guild service exposes creation")
	_check_contains(service_source, "func join_guild", "guild service joins open Guilds")
	_check_contains(service_source, "func apply_to_guild", "guild service submits membership applications")
	_check_contains(service_source, "func cancel_application", "guild service cancels the player's application")
	_check_contains(service_source, '"applicationCooldowns": _array', "guild service preserves application reapply cooldowns")
	_check_contains(service_source, "func load_home", "guild service loads the member dashboard")
	_check_contains(service_source, "func leave_guild", "guild service exposes Guild departure")
	_check_contains(service_source, 'GUILD_HOME_ENDPOINT + "/leave"', "guild departure uses the member endpoint")
	_check_contains(service_source, "func teleport_to_lobby", "guild service exposes the free Lobby teleport")
	_check_contains(service_source, 'AETHER_CLASH_CHALLENGES_ENDPOINT := "/game/aether-clash/challenges"', "guild service uses the Aether Clash challenge endpoint")
	_check_contains(service_source, 'AETHER_CLASH_HISTORY_ENDPOINT := "/game/aether-clash/history"', "guild service uses the protected Guild Duel history endpoint")
	_check_contains(service_source, 'AETHER_CLASH_PLAYER_CHALLENGES_ENDPOINT := "/game/aether-clash/player-challenges"', "guild service uses the player-targeted Aether Clash endpoint")
	_check_contains(service_source, 'AETHER_CLASH_PORTAL_SESSIONS_ENDPOINT := "/game/aether-clash/portal-sessions"', "guild service uses the authoritative Aether Clash portal endpoint")
	_check_contains(service_source, 'AETHER_CLASH_SESSIONS_ENDPOINT := "/game/aether-clash/sessions"', "guild service uses the authoritative Aether Clash arena endpoint")
	_check_contains(service_source, "func load_aether_clash_challenges", "guild service loads incoming, outgoing and current clashes")
	_check_contains(service_source, "func load_aether_clash_history_detail", "guild service loads a completed Guild Duel snapshot")
	_check_contains(service_source, "func create_aether_clash_challenge", "guild leaders and captains can send clash challenges")
	_check_contains(service_source, "func create_aether_clash_player_challenge", "right-click challenges resolve the target player's Guild")
	_check_contains(service_source, '"spectatorAccess": spectator_access', "clash challenges preserve the selected spectator policy")
	_check_contains(service_source, '"tierId": tier_id', "clash challenges send the selected canonical battle tier")
	_check_contains(service_source, '"stakeAmount": maxi(int(stake_amount), 0)', "clash challenges send a non-negative Guild Bank stake")
	_check_contains(service_source, "func load_aether_clash_portal_sessions", "guild service loads accessible portal sessions")
	_check_contains(service_source, "func enter_aether_clash_portal", "guild service requests server-owned portal entry")
	_check_contains(service_source, "func load_aether_clash_arena_state", "guild service loads live Aether Clash arena state")
	_check_contains(service_source, '"matchmaking": _dictionary(body.get("matchmaking", {}))', "guild service preserves personal Aether Clash matchmaking state")
	_check_contains(service_source, '"identifiedEnemyUserIds": _array', "arena state preserves the backward-compatible empty enemy identity field")
	_check_contains(service_source, '"visibleIdentityUserIds": _array', "arena state preserves server-authoritative nameplate visibility")
	_check_contains(service_source, '"viewerRoster": _array', "arena state preserves the privacy-filtered Guild roster")
	_check_contains(service_source, '"recentEliminations": _array', "arena state preserves privacy-filtered elimination notifications")
	_check_contains(service_source, "func leave_aether_clash_arena", "guild service exposes authoritative voluntary Clash departure")
	_check_contains(service_source, 'AETHER_CLASH_SESSIONS_ENDPOINT + "/%s/leave"', "voluntary Clash departure uses the session leave endpoint")
	_check_contains(service_source, "func accept_aether_clash_challenge", "target Guild staff can accept a clash")
	_check_contains(service_source, "func decline_aether_clash_challenge", "target Guild staff can decline a clash")
	_check_contains(service_source, "func cancel_aether_clash_challenge", "challenging Guild staff can cancel a clash")
	_check_contains(service_source, '"pendingIncoming": incoming', "guild service preserves incoming clash challenges")
	_check_contains(service_source, '"currentSession": current_session', "guild service preserves the current reserved clash")
	_check_contains(service_source, '"duelStats": stats', "guild service preserves the Guild Duel record")
	_check_contains(service_source, '"duelHistory": history', "guild service preserves Guild Duel match history")
	_check_contains(service_source, 'entry["ownSide"]', "Guild Duel history preserves which side belongs to the current Guild")
	_check_contains(service_source, 'entry["stakePotAmount"]', "Guild Duel history preserves the settled stake pot")
	_check_contains(service_source, 'detail["participants"] = participants', "Guild Duel details preserve participant records")
	_check_contains(service_source, 'detail["battles"] = battles', "Guild Duel details preserve the battle timeline")
	_check_contains(service_source, "func load_bank", "guild service loads the authoritative Guild Bank")
	_check_contains(service_source, '"itemCapacity": int(body.get("itemCapacity", 50))', "guild service preserves item bank capacity")
	_check_contains(service_source, '"pokemonCapacity": int(body.get("pokemonCapacity", 30))', "guild service preserves Pokémon bank capacity")
	_check_contains(service_source, '"loanUsage": _dictionary', "guild service preserves personal Guild loan usage")
	_check_contains(service_source, "func load_history", "guild service loads membership and rank history")
	_check_contains(service_source, "func load_bank_log", "guild service loads categorized bank logs")
	_check_contains(service_source, '"&search=%s"', "guild service sends server-side log searches")
	_check_contains(service_source, '"&action=%s"', "guild service sends server-side log action filters")
	_check_contains(service_source, '"&dateFrom=%s"', "guild service sends server-side log start dates")
	_check_contains(service_source, '"&dateTo=%s"', "guild service supports future custom log date ranges")
	_check_contains(service_source, 'next_before_id != null else 0', "guild service accepts a null final log cursor")
	_check_contains(service_source, "func deposit_bank_money", "guild service deposits Guild funds")
	_check_contains(service_source, "func withdraw_bank_money", "guild service withdraws Guild funds")
	_check_contains(service_source, "func deposit_bank_item", "guild service deposits Guild items")
	_check_contains(service_source, "func withdraw_bank_item", "guild service withdraws Guild items")
	_check_contains(service_source, "func deposit_bank_resource", "guild service donates consumables to Guild Resources")
	_check_contains(service_source, "func withdraw_bank_resource", "guild service takes consumables from Guild Resources")
	_check_contains(service_source, '"resourceInventory": _array', "guild service preserves personal consumables separately")
	_check_contains(service_source, "func borrow_bank_item", "guild service borrows Guild items without transferring ownership")
	_check_contains(service_source, "func borrow_bank_pokemon", "guild service borrows Guild Pokémon without transferring ownership")
	_check_contains(service_source, "func return_bank_loan_asset", "guild service returns individual borrowed assets")
	_check_contains(service_source, "func force_return_bank_loan_asset", "guild service exposes authorized force returns")
	_check_contains(service_source, "func deposit_bank_pokemon", "guild service deposits or returns Guild Pokémon")
	_check_contains(service_source, "func withdraw_bank_pokemon", "guild service withdraws Guild-owned Pokémon")
	_check_contains(service_source, '"pokemonCandidates": _array', "guild service preserves visible Pokémon donation eligibility")
	_check_contains(service_source, 'GUILD_LOBBY_TELEPORT_ENDPOINT := "/game/guilds/me/lobby/teleport"', "guild service uses the dedicated Lobby endpoint")
	_check_contains(service_source, "func update_settings", "guild service updates leader settings")
	_check_contains(service_source, '"requirements": requirements', "guild service persists the leader's ordered requirement list")
	_check_contains(service_source, '"announcement": announcement.strip_edges()', "guild settings persist the member announcement")
	_check_contains(service_source, '"announcement": str(body.get("announcement", ""))', "guild home preserves the current announcement")
	_check_contains(service_source, '"loanDurationSeconds": loan_duration_seconds', "guild settings preserve the selected loan duration")
	_check_contains(service_source, "func update_member_role", "guild service updates compact Guild ranks")
	_check_contains(service_source, "func kick_member", "guild service removes authorized Guild members")
	_check_contains(service_source, 'HTTPClient.METHOD_DELETE', "Guild member removal uses the dedicated destructive endpoint")
	_check_contains(service_source, "func update_member_bank_permissions", "guild service updates personal Guild Bank rights")
	_check_contains(service_source, '"/members/%d/bank-permissions"', "Guild Bank rights use the dedicated member endpoint")
	_check_contains(service_source, "func update_emblem", "guild service updates the emblem")
	_check_contains(service_source, "func apply_emblem_template", "guild service reapplies Guild-owned emblem templates")
	_check_contains(service_source, '"emblemTemplates": _array', "guild service preserves Guild-owned emblem templates")
	_check_contains(service_source, "signal guild_changed", "guild service publishes emblem changes to the nameplate")
	_check_contains(service_source, "current_guild", "guild service caches the current guild for the local nameplate")
	_check_contains(service_source, "func invite_member", "guild service sends invitations")
	_check_contains(service_source, "func accept_invitation", "guild service accepts invitations")
	_check_contains(service_source, "func decline_invitation", "guild service declines invitations")
	_check_contains(service_source, "func cancel_invitation", "guild service cancels invitations")
	_check_contains(service_source, "func accept_application", "guild service accepts membership applications")
	_check_contains(service_source, "func decline_application", "guild service declines membership applications")
	_check_contains(service_source, "signal notification_received", "guild service exposes durable application notifications")
	_check_contains(service_source, "func _poll_notifications", "guild service polls application decisions missed while offline")
	_check_contains(service_source, 'GUILD_NOTIFICATIONS_ENDPOINT + "/%d/ack"', "guild service acknowledges displayed application decisions")
	_check_contains(service_source, '"pendingApplications": _array', "guild service preserves pending applications")
	_check_contains(service_source, '"rankPermissions": _dictionary', "guild service preserves authoritative rank permissions")
	_check_contains(project_source, 'GuildService="*res://scripts/services/guild_service.gd"', "guild service is available as an autoload")

	quit(1 if failed else 0)


func _check_contains(source: String, expected: String, label: String) -> void:
	if source.contains(expected):
		print("PASS %s" % label)
		return
	failed = true
	push_error(label)
