extends SceneTree

const GUILD_POPUP_SCENE_PATH := "res://scenes/interface/guild_popup.tscn"
const GUILD_POPUP_SCRIPT_PATH := "res://scripts/ui/guild_popup.gd"
const OVERLAY_SCRIPT_PATH := "res://scripts/ui/ui_overlay.gd"

var failed := false


func _init() -> void:
	var popup_scene_source := FileAccess.get_file_as_string(GUILD_POPUP_SCENE_PATH)
	var popup_source := FileAccess.get_file_as_string(GUILD_POPUP_SCRIPT_PATH)
	var overlay_source := FileAccess.get_file_as_string(OVERLAY_SCRIPT_PATH)

	_check_contains(popup_scene_source, "guild_popup.gd", "guild popup scene loads its controller")
	_check_contains(popup_source, '"ui.guild.title"', "guildless interface has a localized title")
	_check_contains(popup_source, '"ui.guild.tab.browse"', "guildless interface exposes localized guild discovery")
	_check_contains(popup_source, '"ui.guild.tab.create"', "guildless interface exposes localized guild creation")
	_check_contains(popup_source, "func _build_directory_filter_dialog", "guild directory exposes its filters in one dialog")
	_check_contains(popup_source, "func _render_guild_list", "guild directory renders a compact guild list")
	_check_contains(popup_source, "GuildRowContacts_", "Guild directory identifies Captain contacts")
	_check_contains(popup_source, "func _render_selected_guild", "selected guild has a public information panel")
	_check_contains(popup_source, "func _apply_to_selected_guild", "guild discovery submits real membership applications")
	_check_contains(popup_source, "GuildApplicationRequirementsDialog", "applicants review Guild requirements before applying")
	_check_contains(popup_source, "GuildApplicationCooldown", "declined Guild applications explain their reapply cooldown")
	_check_contains(popup_source, "func _application_cooldown_for_guild", "Guild discovery evaluates authoritative reapply cooldowns")
	_check_contains(popup_source, "GuildRequirementsPanel", "configured Guild requirements render as a dedicated profile section")
	_check_contains(popup_source, "GuildAddRequirementButton", "Guild leaders can add requirements individually")
	_check_contains(popup_source, "func _on_move_guild_requirement", "Guild leaders can order their requirements")
	_check_contains(popup_source, "func _on_remove_guild_requirement", "Guild leaders can remove individual requirements")
	_check_contains(popup_source, "_player_badge_count()", "objective badge requirements show the applicant's current status")
	_check_contains(popup_source, "func _join_selected_guild", "open Guilds support direct joining")
	_check_contains(popup_source, "GuildJoinConfirmationDialog", "direct joining requires confirmation")
	_check_contains(popup_source, '"ui.guild.row.discovery"', "guild cards show focus and language")
	_check_contains(popup_source, '"ui.guild.create.emblem_note"', "creation flow explains the optional emblem through localization")
	_check_contains(popup_source, "CREATION_COST := 100000", "creation flow shows the Pokédollar gate")
	_check_contains(popup_source, "REQUIRED_BADGES := 3", "creation flow shows the badge gate")
	_check_contains(popup_source, "_player_badge_count() < REQUIRED_BADGES", "creation flow evaluates server badge progress")
	_check_contains(popup_source, '"create_guild"', "creation flow calls the authoritative guild service")
	_check_contains(popup_source, '"apply_wallet_result"', "successful creation applies the charged wallet")
	_check_contains(popup_source, "func _render_guild_home", "guild members receive a dedicated dashboard")
	_check_contains(popup_source, '_show_page("member" if not membership.is_empty() else "browse")', "guild members land on their own dashboard")
	_check_contains(popup_source, "has_explicit_page_selection", "explicit guild navigation is preserved")
	_check_contains(popup_source, "GuildOverviewTab", "guild dashboard separates its overview")
	_check_contains(popup_source, "GuildBankTab", "guild dashboard provides a dedicated bank workspace")
	_check_contains(popup_source, "GuildAetherClashTab", "guild dashboard provides a dedicated Aether Clash workspace")
	_check_contains(popup_source, "GuildAetherClashChallengeButton", "authorized Guild staff can challenge a selected Guild")
	_check_contains(popup_source, "GuildAetherClashDuelModeTab", "Aether Clash separates Guild Duel into its own mode tab")
	_check_contains(popup_source, "GuildAetherClashBattleRoyaleModeTab", "Aether Clash reserves a mode tab for Battle Royale")
	_check_contains(popup_source, "GuildAetherClashDuelStats", "Guild Duel shows the Guild record")
	_check_contains(popup_source, "GuildAetherClashDuelHistory", "Guild Duel shows recent match history")
	_check_contains(popup_source, "func _open_aether_clash_history_detail", "Guild Duel history entries open their full details")
	_check_contains(popup_source, "GuildAetherClashHistoryDetailWindow", "Guild Duel details use a dedicated themed window")
	_check_contains(popup_source, "func _build_aether_clash_history_participant_row", "Guild Duel details show individual records and final status")
	_check_contains(popup_source, "func _build_aether_clash_history_battle_row", "Guild Duel details show a chronological battle timeline")
	_check_contains(popup_source, "GuildCurrentAetherClash", "every Guild member can see the reserved clash")
	_check_contains(popup_source, "GuildAetherClashEntryCountdown", "accepted clashes show the lobby entry countdown")
	_check_contains(popup_source, "GuildAetherClashSpectatorAccess", "challenge creators configure spectator access")
	_check_contains(popup_source, "GuildAetherClashTier", "challenge creators choose the canonical battle tier")
	_check_contains(popup_source, "GuildAetherClashStakeAmount", "challenge creators can fund a stake from both Guild Banks")
	_check_contains(popup_source, "RetryGuildAetherClashButton", "failed Aether Clash loading exposes an explicit retry action")
	_check_contains(popup_source, "aether_clash_load_error", "failed Aether Clash loading replaces the indefinite loading state")
	_check_contains(popup_source, "AETHER_CONFIRMATION_DIALOG_SCENE.instantiate()", "Guild challenge confirmation uses the themed Aether modal")
	_check_contains(popup_source, '_aether_clash_spectator_access_text(str(challenge.get("spectatorAccess", "public")))', "challenge cards show their spectator policy")
	_check_contains(popup_source, "_aether_clash_contract_text(challenge)", "challenge cards show tier, stake and pot")
	_check_contains(popup_source, 'in ["leader", "captain"]', "challenge controls are restricted to Leaders and Captains")
	_check_contains(popup_source, "GuildAnnouncementPanel", "guild overview is dedicated to Guild announcements")
	_check_contains(popup_source, "GuildOptionsMenuButton", "Guild departure lives in a low-prominence options menu")
	_check_contains(popup_source, "GuildProgressionPanel", "guild overview renders shared level progression")
	_check_contains(popup_source, 'str(int(guild.get("level", 1)))', "guild overview displays whole-number Guild levels")
	_check_contains(popup_source, "GuildPresencePanel", "guild overview summarizes currently online members")
	_check_contains(popup_source, "GuildExperienceProgress", "guild overview renders the Guild EXP progress bar")
	_check_contains(popup_source, "GuildLevelRewardsButton", "guild progression exposes the complete level roadmap")
	_check_contains(popup_source, "GuildLevelRewardsWindow", "guild level roadmap opens in a dedicated modal")
	_check_contains(popup_source, "GuildLevelRewardRow_", "guild level roadmap renders each level separately")
	_check_contains(popup_source, "GuildLeaveConfirmationDialog", "Guild departure requires confirmation")
	_check_contains(popup_source, "func _leave_current_guild", "Guild departure calls the authoritative service")
	_check_contains(popup_source, '_show_guild_system_message("ui.guild.leave.success"', "departing Trainer receives a system message")
	_check_contains(popup_source, "GuildHeaderTravelActions", "guild travel occupies the member header")
	_check_contains(popup_source, "header.add_child(_build_guild_header_travel_actions(guild, is_leader))", "member header replaces recruitment status with travel actions")
	_check_contains(popup_source, "guild_section_navigation.visible = true", "Guild members receive section tabs in the primary navigation")
	_check_contains(popup_source, "browse_tab_button.custom_minimum_size = Vector2(150, 34)", "Guild discovery becomes compact for existing members")
	_check_contains(popup_source, "GuildLobbyTeleportButton", "guild travel exposes Aether Clash Lobby travel")
	_check_contains(popup_source, "GuildBaseTeleportButton", "guild travel previews the future Guild Base destination")
	_check_contains(popup_source, '"ui.guild.lobby.teleport"', "Lobby travel action is localized")
	_check_contains(popup_source, "func _build_guild_funds_workspace", "Guild Bank provides shared-funds transactions")
	_check_contains(popup_source, "func _build_guild_pokemon_workspace", "Guild Bank provides Guild-owned Pokémon storage")
	_check_contains(popup_source, "func _build_guild_items_workspace", "Guild Bank provides item storage transactions")
	_check_contains(popup_source, "func _build_guild_resources_workspace", "Guild Bank provides freely shared consumable resources")
	_check_contains(popup_source, '"resource_deposit"', "Guild Resources support individually managed deposit access")
	_check_contains(popup_source, '"resource_withdraw"', "Guild Resources support individually managed withdrawal access")
	_check_contains(popup_source, "func _build_guild_borrowed_item_list", "Guild Bank lists each borrowed item separately")
	_check_contains(popup_source, '"ui.guild.bank.force_return"', "Guild Bank exposes the staff force-return action")
	_check_contains(popup_source, "_selected_guild_loan_duration", "Guild leaders can choose the loan duration")
	_check_contains(popup_source, 'guild.get("loanDurationSeconds", 3600)', "Guild settings default loans to one hour")
	_check_contains(popup_source, "GuildHistoryLogButton", "member roster opens its dedicated Guild history")
	_check_contains(popup_source, '"GuildBank%sLogButton"', "each Guild Bank category opens its own log")
	_check_contains(popup_source, "GuildLogSearchInput", "every Guild log exposes server-side search")
	_check_contains(popup_source, "GuildLogActionFilter", "every Guild log can filter by action")
	_check_contains(popup_source, '"clash_stake_hold", "clash_stake_refund", "clash_stake_payout"', "Guild Bank logs can filter Aether Clash escrow movements")
	_check_contains(popup_source, '"ui.guild.log.aether_clash.%s" % action', "Guild Bank logs explain Aether Clash escrow movements")
	_check_contains(popup_source, "GuildLogClearFiltersButton", "Guild log filters can be cleared")
	_check_contains(popup_source, "GuildLogTitleBar", "Guild logs replace the native title bar with a visible Guild header")
	_check_contains(popup_source, "GuildLogCloseButton", "Guild logs provide a clearly styled close action")
	_check_contains(popup_source, "_build_guild_log_message", "Guild logs render refinable rich-text messages")
	_check_contains(popup_source, "_guild_log_player_names", "Guild logs derive highlights from structured player fields")
	_check_contains(popup_source, "message.push_color(UI_ACCENT)", "Guild log player names receive the Guild accent colour")
	_check_contains(popup_source, "GuildLogActionField", "Guild log action choices have a visible field label")
	_check_contains(popup_source, "GuildLogPeriodFilter", "every Guild log offers useful recent time periods")
	_check_contains(popup_source, "Time.get_datetime_string_from_unix_time", "Guild log periods use an absolute UTC boundary")
	_check_contains(popup_source, "GuildBankDonationConfirmationDialog", "donations explain permanent Guild ownership")
	_check_contains(popup_source, "GuildBankItemIcon_", "Guild Bank item rows render icons")
	_check_contains(popup_source, "GuildBankItemDetail_", "Guild Bank item rows separate availability from the item name")
	_check_contains(popup_source, "_guild_bank_total_item_quantity", "Guild Item Storage reports total item quantity separately from stack capacity")
	_check_contains(
		popup_source,
		'"ui.guild.bank.resources.count", {\n\t\t\t\t"count": _array_from_value(guild_bank_state.get("resources", [])).size(),\n\t\t\t\t"capacity": int(guild_bank_state.get("itemCapacity", 50))',
		"Guild Resources show their stack capacity"
	)
	_check_contains(popup_source, "GuildBankPokemonIcon_", "Guild Bank Pokémon rows render icons")
	_check_contains(popup_source, "_open_guild_bank_pokemon_summary", "Guild Bank Pokémon open the read-only Summary")
	_check_contains(popup_source, "func _show_guild_item_storage_window", "large Guild item stores open separate management windows")
	_check_contains(popup_source, "func _build_guild_item_description", "selected Guild items and Resources show a dedicated description card")
	_check_contains(popup_source, 'has_method("short_description")', "Guild item descriptions use the localized item catalog")
	_check_contains(popup_source, 'return "GuildItemsStorage" if category == "items" else "GuildResourcesStorage"', "Items and Resources receive dedicated full-window browsers")
	_check_contains(popup_source, 'search.name = "%sSearchInput" % prefix', "full Guild item stores provide search")
	_check_contains(popup_source, 'filter.name = "%sFilterSelect" % prefix', "full Guild item stores provide filters")
	_check_contains(popup_source, "grid.columns = 5", "full Guild item stores use a compact asset grid")
	_check_contains(popup_source, "GuildBankPokemonListScroll", "Guild Pokémon previews remain scrollable")
	_check_contains(popup_source, "GuildPokemonVaultWindow", "full Pokémon Vault opens in a dedicated window")
	_check_contains(popup_source, "GuildPokemonVaultGrid", "full Pokémon Vault presents a PC-like grid")
	_check_contains(popup_source, "GuildPokemonVaultSelectedActions", "selected Guild Pokémon expose contextual actions")
	_check_contains(popup_source, "GuildPokemonVaultStatusPanel", "full Pokémon Vault keeps action feedback visible")
	_check_contains(popup_source, "GuildBankItemListScroll", "Guild item and Resource previews remain scrollable")
	_check_contains(popup_source, "GuildBankPermissionSummary", "Guild Bank explains the current rank's transaction rights")
	_check_contains(popup_source, "GuildBankRankRightsWorkspace", "Guild Bank exposes a complete rank-rights page")
	_check_contains(popup_source, 'guild_home.get("rankPermissions", {})', "Guild rank rights use the authoritative server matrix")
	_check_contains(popup_source, "amount.min_value = 0", "Guild Bank money starts from a neutral zero value")
	_check_contains(popup_source, "amount.value = 0", "Guild Bank money initially displays zero")
	_check_contains(popup_source, "amount.update_on_text_changed = true", "Guild Bank money uses the amount currently typed")
	_check_contains(popup_source, "amount.step = 1", "Guild Bank money accepts every whole amount")
	_check_contains(popup_source, "lendingEnabled", "Guild Bank borrowing follows server availability")
	_check_contains(popup_source, "_guild_bank_borrow_tooltip", "disabled Guild Bank borrowing explains why")
	_check_contains(popup_source, "func _guild_bank_loan_usage_text", "Guild Bank categories expose personal loan usage")
	_check_contains(popup_source, "_guild_bank_loan_limit_reached", "Guild borrowing respects the visible personal loan limit")
	_check_contains(popup_source, "pokemonTradeLevelCap", "Guild Pokémon actions use the player's trade level cap")
	_check_contains(popup_source, "_guild_bank_pokemon_level_cap_tooltip", "blocked Pokémon transfers explain their level cap")
	_check_contains(popup_source, "func _on_player_party_changed", "Guild Pokémon storage refreshes after Party changes")
	_check_contains(popup_source, 'member_status_label.name = "GuildMemberStatus"', "Guild action feedback has a visible named status row")
	_check_contains(popup_source, "_render_guild_home_with_status", "Guild Bank feedback survives workspace refreshes")
	_check_contains(popup_source, "GuildMemberActionsButton_", "Guild member management uses one compact action menu")
	_check_contains(popup_source, "GUILD_MEMBER_MANAGE_ICON", "Guild member management uses a recognizable action icon")
	_check_contains(popup_source, 'popup.add_separator(_t("ui.guild.member.menu_management"))', "Guild member actions visually separate management controls")
	_check_contains(popup_source, "GUILD_MEMBER_REMOVE_ICON", "destructive Guild member actions have distinct styling")
	_check_contains(popup_source, "GUILD_MEMBER_ACTION_CHANGE_RANK", "Guild leaders can change ranks from member actions")
	_check_contains(popup_source, "GUILD_MEMBER_ACTION_BANK_RIGHTS", "permission managers can edit member Guild Bank rights")
	_check_contains(popup_source, "GUILD_MEMBER_ACTION_KICK", "Guild Leaders and Captains can remove members from member actions")
	_check_contains(popup_source, "GuildMemberKickDialog_", "Guild member removal requires confirmation")
	_check_contains(popup_source, "func _build_guild_member_actions_button", "member controls stay grouped behind one action button")
	_check_contains(popup_source, "func _open_guild_member_bank_permissions", "Guild Bank rights open as per-member overrides")
	_check_contains(popup_source, '"update_member_bank_permissions"', "Guild Bank permission changes use the authoritative service")
	_check_contains(popup_source, "bankPermissionOverrides", "Guild Bank feedback distinguishes personal permission denials")
	_check_contains(popup_source, "GuildMemberPresenceLabel_", "Guild member cards show online and last-seen state")
	_check_contains(popup_source, "GuildMemberAvatar_", "Guild member cards show compact sprite-based Trainer portraits")
	_check_contains(popup_source, "GuildMemberContributionLabel_", "Guild member cards show contributed Guild EXP")
	_check_contains(popup_source, "GUILD_MEMBER_ACTION_PM", "Guild member action menus expose private messages")
	_check_contains(popup_source, "GuildMembersTab", "guild dashboard separates its member roster")
	_check_contains(popup_source, "GuildManagementTab", "guild dashboard separates management controls")
	_check_contains(popup_source, "GuildManagementNavigation", "Guild management uses an organized secondary navigation")
	_check_contains(popup_source, "GuildManagementProfilePage", "Guild profile settings have a dedicated management page")
	_check_contains(popup_source, "GuildManagementRecruitmentPage", "Guild recruitment settings have a dedicated management page")
	_check_contains(popup_source, '"applications":\n\t\t\tworkspace.add_child(_build_guild_applications())', "Guild staff receive a dedicated application management page")
	_check_contains(popup_source, "GuildManagementBankPage", "Guild Bank settings have a dedicated management page")
	_check_contains(popup_source, "GuildManagementNotificationBadge", "primary management navigation shows pending applications")
	_check_contains(popup_source, "GuildApplicationsNotificationBadge", "pending applications show an attention badge")
	_check_contains(popup_source, "ViewGuildApplicantTrainerCardButton_", "Guild applications link to the applicant's Trainer Card")
	_check_contains(popup_source, "func _render_pending_applications", "Guild staff can review pending applications")
	_check_contains(popup_source, '"ui.guild.roster"', "guild dashboard renders its localized member roster")
	_check_contains(popup_source, "GUILD_EMBLEM_SIZE := 32", "guild emblems use the intended 32 by 32 resolution")
	_check_contains(popup_source, "EditGuildEmblemIconButton", "clicking the Guild emblem opens its editor")
	_check_contains(popup_source, '"ui.guild.emblem.edit"', "editable guild emblem explains its localized action")
	_check_contains(popup_source, "GuildEmblemEditorPopup", "guild emblem editor uses a dedicated popup")
	_check_contains(popup_source, "GuildEmblemColorCode", "guild emblem palette accepts exact hex colour codes")
	_check_contains(popup_source, "GuildSavedEmblemSelect", "guild emblem editor lists Guild-owned templates")
	_check_contains(popup_source, "ApplySavedGuildEmblemButton", "guild emblem editor can restore a Guild-owned template")
	_check_contains(popup_source, '"ui.guild.invite.title"', "guild leaders and captains can invite trainers")
	_check_contains(popup_source, "GuildMemberSearchInput", "member roster provides current-member search")
	_check_contains(popup_source, "OpenGuildInviteDialogButton", "member invitations use a separate roster action")
	_check_contains(popup_source, '"ui.guild.invite.action"', "member invitation action clearly names its purpose")
	_check_contains(popup_source, "GuildInviteDialog", "member invitations open in a dedicated dialog")
	_check_contains(popup_source, "func _apply_guild_confirmation_style", "Guild confirmations share dedicated styling")
	_check_contains(popup_source, "func _apply_guild_window_style", "Guild windows share dedicated styling")
	_check_contains(popup_source, "func _apply_guild_popup_panel_style", "Guild popup panels share dedicated styling")
	_check_contains(popup_source, "func _apply_popup_menu_style", "Guild dropdown menus share dedicated styling")
	_check_contains(popup_source, "func _on_accept_invitation", "guildless trainers can accept invitations")
	_check_contains(overlay_source, "GUILD_POPUP_SCENE", "main overlay loads the guild popup")
	_check_contains(overlay_source, "_open_guild_popup()", "existing guild button opens the new interface")
	_check_contains(overlay_source, "_on_guild_private_message_requested", "main overlay opens private chat from the Guild roster")
	_check_contains(overlay_source, "_on_guild_trainer_card_requested", "main overlay opens public Trainer Cards from Guild applications")
	_check_contains(overlay_source, '"guild.application.updated", "guild.notification.received"', "main overlay receives realtime Guild notifications")
	_check_contains(overlay_source, "_on_guild_notification_received", "Guild application decisions become system messages")
	_check_contains(overlay_source, '"ui.guild.notification.member_left"', "Guild departures become system messages")
	_check_contains(overlay_source, '"ui.guild.notification.member_kicked"', "removed Guild members receive a system message")
	_check_contains(overlay_source, '"ui.guild.notification.aether_clash_received"', "Aether Clash challenges become system messages")
	_check_contains(overlay_source, "IncomingAetherClashChallengeDialog", "incoming Aether Clash challenges open a direct response modal")
	_check_contains(overlay_source, "IncomingAetherClashCountdown", "incoming Aether Clash modal shows its response deadline")
	_check_contains(overlay_source, "accept_aether_clash_challenge", "incoming Aether Clash modal can accept directly")
	_check_contains(overlay_source, "decline_aether_clash_challenge", "incoming Aether Clash modal can decline directly")
	_check_contains(overlay_source, "_refresh_after_aether_clash_notification", "Aether Clash notifications refresh an open Guild screen")
	_check_contains(overlay_source, "_on_guild_lobby_teleport_requested", "main overlay applies the authorized Lobby teleport")

	quit(1 if failed else 0)


func _check_contains(source: String, expected: String, label: String) -> void:
	if source.contains(expected):
		print("PASS %s" % label)
		return
	failed = true
	push_error(label)
