extends SceneTree

func _initialize() -> void:
	var stage := Control.new()
	root.add_child(stage)
	stage.size = Vector2(263, 180)
	var background := ColorRect.new()
	stage.add_child(background)
	var surface := SubViewportContainer.new()
	stage.add_child(surface)
	var diagnostic = load("res://scripts/ui/preview_surface_diagnostic.gd").attach(stage, surface)
	assert(diagnostic != null)
	assert(diagnostic.mode == 0)
	assert(diagnostic.get_index() < surface.get_index())
	assert(diagnostic.get_index() > background.get_index())
	assert(diagnostic.mouse_filter == Control.MOUSE_FILTER_IGNORE)
	diagnostic.set_mode(3)
	assert(diagnostic.z_index == 100)
	diagnostic.set_mode(0)
	assert(diagnostic.z_index == 0)
	assert(surface.visible)
	print("PASS preview surface diagnostic: ordering, isolation, reset")
	quit()
