extends SceneTree

const CHECK_SCRIPTS: Array[String] = [
	"res://tests/battle_display_data_presenter_check.gd",
	"res://tests/pokemon_nickname_battle_ui_check.gd",
	"res://tests/npc_battle_team_reveal_check.gd",
	"res://tests/held_item_stat_modifier_check.gd",
	"res://tests/held_item_drag_drop_check.gd",
	"res://tests/party_slot_context_menu_check.gd",
	"res://tests/trainer_interaction_ownership_check.gd",
	"res://tests/trainer_first_encounter_marker_check.gd",
	"res://tests/battle_party_slot_resolver_check.gd",
	"res://tests/training_room_battle_team_contract_check.gd",
	"res://tests/battle_event_text_formatter_check.gd",
	"res://tests/battle_message_timing_check.gd",
	"res://tests/battle_event_presentation_check.gd",
	"res://tests/battle_presentation_state_check.gd",
	"res://tests/battle_state_field_delta_check.gd",
	"res://tests/battle_render_barrier_check.gd",
	"res://tests/pvp_prechoice_buffer_check.gd",
	"res://tests/battle_response_order_check.gd",
	"res://tests/battle_result_overlay_check.gd",
	"res://tests/battle_event_renderer_order_check.gd",
	"res://tests/battle_voice_director_check.gd",
	"res://tests/battle_voice_timing_check.gd",
	"res://tests/battle_rewind_helper_check.gd",
	"res://tests/battle_event_pre_render_order_check.gd",
	"res://tests/battle_state_deferred_hp_check.gd",
	"res://tests/battle_state_hp_cursor_check.gd",
	"res://tests/battle_state_primal_forms_check.gd",
	"res://tests/battle_state_battle_bond_check.gd",
	"res://tests/mega_champions_catalog_check.gd",
	"res://tests/mega_champions_phase3_data_check.gd",
	"res://tests/mega_champions_phase4_generator_payload_check.gd",
	"res://tests/mega_generator_mode_routing_check.gd",
	"res://tests/battle_mechanical_suspension_state_check.gd",
	"res://tests/battle_timer_projection_check.gd",
	"res://tests/battle_timer_ui_visibility_check.gd",
	"res://tests/battle_participant_privacy_contract_check.gd",
	"res://tests/battle_pokemon_hover_level_check.gd",
	"res://tests/battle_calcdex_snapshot_check.gd",
	"res://tests/battle_calcdex_inference_check.gd",
	"res://tests/battle_damage_calc_hp_scale_check.gd",
	"res://tests/pvp_team_preview_privacy_completion_check.gd",
	"res://tests/team_preview_layer_lifecycle_check.gd",
	"res://tests/pvp_privacy_render_resolution_check.gd",
	"res://tests/battle_z_move_type_icons_check.gd",
	"res://tests/battle_vs_panel_layout_check.gd",
	"res://tests/moves_grid_disabled_state_check.gd",
	"res://tests/battle_ui_layout_check.gd",
	"res://tests/battle_trainer_staging_check.gd",
	"res://tests/battle_animation_anchor_check.gd",
	"res://tests/battle_terrain_field_visual_check.gd",
	"res://tests/status_condition_overlay_check.gd",
	"res://tests/field_timer_animated_terrain_icon_check.gd",
	"res://tests/battle_substitute_presentation_check.gd",
	"res://tests/party_slot_hp_payload_check.gd",
	"res://tests/pokemon_ball_metadata_check.gd",
	"res://tests/pokemon_home_icon_resolution_check.gd",
	"res://tests/pokemon_cry_resolver_check.gd",
	"res://tests/pokemon_cry_audio_settings_check.gd",
	"res://tests/item_acquisition_audio_check.gd",
	"res://tests/localization_foundation_check.gd",
	"res://tests/localization_shared_ui_check.gd",
	"res://tests/localization_party_summary_check.gd",
	"res://tests/pokemon_nickname_payload_check.gd",
	"res://tests/pokemon_nickname_ui_check.gd",
	"res://tests/localization_bag_hotbar_check.gd",
	"res://tests/localization_battle_ui_check.gd",
	"res://tests/localization_item_data_check.gd",
	"res://tests/localization_content_data_check.gd",
	"res://tests/localization_backend_error_check.gd",
	"res://tests/account_email_login_check.gd",
	"res://tests/privacy_account_controls_check.gd",
	"res://tests/client_version_contract_check.gd",
	"res://tests/client_crash_reporting_check.gd",
	"res://tests/senior_staff_permission_projection_check.gd",
	"res://tests/tester_tool_permissions_check.gd",
	"res://tests/localization_launcher_news_check.gd",
	"res://tests/localization_market_ui_check.gd",
	"res://tests/localization_pokedex_ui_check.gd",
	"res://tests/town_map_ui_check.gd",
	"res://tests/localization_mail_ui_check.gd",
	"res://tests/localization_friendlist_ui_check.gd",
	"res://tests/localization_storage_ui_check.gd",
	"res://tests/localization_pvp_ui_check.gd",
	"res://tests/localization_trainer_card_ui_check.gd",
	"res://tests/dev_currency_button_icons_check.gd",
	"res://tests/spinbox_live_input_check.gd",
	"res://tests/localization_chat_buff_ui_check.gd",
	"res://tests/session_logout_warning_check.gd",
	"res://tests/localization_item_dex_wild_tools_check.gd",
	"res://tests/localization_progression_world_ui_check.gd",
	"res://tests/localization_release_candidates_check.gd",
	"res://tests/pokemon_happiness_payload_check.gd",
	"res://tests/pokemon_experience_payload_check.gd",
	"res://tests/pokemon_level_cap_check.gd",
	"res://tests/pokemon_factory_hp_snapshot_check.gd",
	"res://tests/pokemon_pc_interactable_check.gd",
	"res://tests/new_player_spawn_check.gd",
	"res://tests/map_transition_fade_check.gd",
	"res://tests/blackout_respawn_contract_check.gd",
	"res://tests/world_area_access_contract_check.gd",
	"res://tests/world_activity_recovery_check.gd",
	"res://tests/map_character_route_gate_check.gd",
	"res://tests/world_access_catalog_generation_check.gd",
	"res://tests/route_2_house_transition_check.gd",
	"res://tests/evolution_prompt_queue_check.gd",
	"res://tests/gameplay_reset_contract_check.gd",
	"res://tests/game_state_scoped_input_lock_check.gd",
	"res://tests/story_service_contract_check.gd",
	"res://tests/dev_story_checkpoint_world_state_check.gd",
	"res://tests/starter_choice_dialog_check.gd",
	"res://tests/oaks_lab_gary_sequence_check.gd",
	"res://tests/quest_journal_contract_check.gd",
	"res://tests/market_attendant_npc_check.gd",
	"res://tests/cursor_theme_check.gd",
	"res://tests/pixel_perfect_rendering_check.gd",
	"res://tests/story_interaction_contract_check.gd",
	"res://tests/story_trigger_lock_retry_check.gd",
	"res://tests/mentor_help_menu_check.gd",
	"res://tests/players_house_story_intro_check.gd",
	"res://tests/rivals_house_daisy_check.gd",
	"res://tests/impersonation_account_switch_check.gd",
	"res://tests/floor_visibility_mask_camera_check.gd",
	"res://tests/tall_grass_character_depth_check.gd",
	"res://tests/players_house_visual_depth_check.gd",
	"res://tests/players_house_location_label_check.gd",
	"res://tests/map_music_profile_check.gd",
	"res://tests/map_layer_resolver_check.gd",
	"res://tests/horizontal_stair_elevation_check.gd",
	"res://tests/outdoor_horizontal_stair_markers_check.gd",
	"res://tests/mt_moon_trainer_layout_check.gd",
	"res://tests/mt_moon_wild_encounter_check.gd",
	"res://tests/mt_moon_item_layout_check.gd",
	"res://tests/early_kanto_item_layout_check.gd",
	"res://tests/mt_moon_story_layout_check.gd",
	"res://tests/mt_moon_ambush_cinematic_check.gd",
	"res://tests/mt_moon_transition_facing_check.gd",
	"res://tests/route_4_mt_moon_transition_check.gd",
	"res://tests/pokemon_center_template_structure_check.gd",
	"res://tests/aether_atelier_check.gd",
	"res://tests/aether_atelier_runtime_check.gd",
	"res://tests/aether_exchange_check.gd",
	"res://tests/sign_interactable_check.gd",
	"res://tests/sign_content_validation_check.gd",
	"res://tests/pokemon_storage_service_contract_check.gd",
	"res://tests/pvp_ranked_banlists_check.gd",
	"res://tests/pvp_ranked_team_validation_check.gd",
	"res://tests/pvp_battle_realtime_stream_check.gd",
	"res://tests/pvp_observability_check.gd",
	"res://tests/pvp_spectator_terminal_check.gd",
	"res://tests/pvp_battle_history_reference_check.gd",
	"res://tests/map_encounter_provider_check.gd",
	"res://tests/surf_activity_presence_check.gd",
	"res://tests/surf_mount_render_check.gd",
	"res://tests/mount_management_ui_check.gd",
	"res://tests/skills_ui_check.gd",
	"res://tests/ev_training_check.gd",
	"res://tests/fishing_inventory_check.gd",
	"res://tests/fishing_action_controller_check.gd",
	"res://tests/fishing_hotkey_settings_check.gd",
	"res://tests/pickpocket_pose_check.gd",
	"res://tests/thieving_position_check.gd",
	"res://tests/thieving_mentor_reward_check.gd",
	"res://tests/thieving_foundation_check.gd",
	"res://tests/rock_smash_foundation_check.gd",
	"res://tests/wild_encounter_error_rules_check.gd",
	"res://tests/wild_encounter_transition_check.gd",
	"res://tests/pallet_town_encounter_check.gd",
	"res://tests/pallet_town_play_family_check.gd",
	"res://tests/route_2_viridian_forest_encounter_check.gd",
	"res://tests/route_2_viridian_forest_gate_transition_check.gd",
	"res://tests/ambient_overworld_pokemon_check.gd",
	"res://tests/wild_pokemon_map_popup_check.gd",
	"res://tests/location_status_card_check.gd",
	"res://tests/loading_screen_layout_check.gd",
	"res://tests/launcher_self_update_check.gd",
	"res://tests/launcher_diagnostics_check.gd",
	"res://tests/credits_access_check.gd",
	"res://tests/world_time_service_check.gd",
	"res://tests/day_night_system_check.gd",
	"res://tests/night_light_check.gd",
	"res://tests/field_move_flash_light_check.gd",
	"res://tests/overworld_field_interactables_check.gd",
	"res://tests/overworld_item_interaction_runtime_check.gd",
	"res://tests/overworld_item_notification_check.gd",
	"res://tests/building_window_light_check.gd",
	"res://tests/developer_world_time_selector_check.gd",
	"res://tests/overworld_weather_controller_check.gd",
	"res://tests/content_creator_photo_mode_check.gd",
	"res://tests/hide_other_players_setting_check.gd",
	"res://tests/player_name_visibility_setting_check.gd",
	"res://tests/pokemon_summary_move_reorder_check.gd",
	"res://tests/pokemon_summary_direct_field_move_check.gd",
	"res://tests/pokemon_readonly_summary_check.gd",
	"res://tests/pokemon_summary_fixed_size_check.gd",
	"res://tests/tmx_visual_importer_check.gd",
	"res://tests/viridian_visual_jail_check.gd",
	"res://tests/open_field_visual_check.gd",
	"res://tests/social_service_contract_check.gd",
	"res://tests/guild_service_contract_check.gd",
	"res://tests/guild_popup_check.gd",
	"res://tests/guild_popup_runtime_check.gd",
	"res://tests/guild_invitation_dialog_check.gd",
	"res://tests/guild_nameplate_runtime_check.gd",
	"res://tests/badge_progression_check.gd",
	"res://tests/trainer_card_gym_badges_runtime_check.gd",
	"res://tests/dev_badge_progress_popup_runtime_check.gd",
	"res://tests/gym_leader_alpha_hub_check.gd",
	"res://tests/npc_definition_profile_check.gd",
	"res://tests/trade_service_contract_check.gd",
	"res://tests/trade_item_workspace_check.gd",
	"res://tests/trade_realtime_service_check.gd",
	"res://tests/trade_invitation_dialog_check.gd",
	"res://tests/trade_workspace_check.gd",
	"res://tests/localization_trade_ui_check.gd",
	"res://tests/trade_two_client_offer_check.gd",
	"res://tests/trade_disconnect_lifecycle_check.gd",
	"res://tests/trade_confirmation_completion_check.gd",
	"res://tests/trade_operations_client_check.gd",
	"res://tests/world_presence_roster_check.gd",
	"res://tests/player_interaction_coordinator_check.gd",
	"res://tests/npc_identity_check.gd",
	"res://tests/npc_metadata_role_boundary_check.gd",
	"res://tests/npc_dialogue_metadata_check.gd",
	"res://tests/npc_dialogue_resolver_check.gd",
	"res://tests/dialogue_metadata_service_check.gd",
	"res://tests/dialogue_input_lock_check.gd",
	"res://tests/npc_dialogue_latency_check.gd",
	"res://tests/trainer_dialogue_cleanup_check.gd",
	"res://tests/npc_content_validation_check.gd",
	"res://tests/item_gift_npc_check.gd",
	"res://tests/overworld_pokemon_check.gd",
	"res://tests/overworld_medicine_check.gd",
	"res://tests/player_action_escape_rope_check.gd",
	"res://tests/overworld_ui_side_layout_check.gd",
	"res://tests/global_heal_check.gd",
	"res://tests/global_heal_dialog_runtime_check.gd",
	"res://tests/adinho_appearance_unlock_check.gd",
	"res://tests/base_hair_layer_check.gd",
	"res://tests/appearance_color_system_check.gd",
	"res://tests/donator_store_cosmetic_subtabs_check.gd",
	"res://tests/blessed_chat_badge_check.gd",
	"res://tests/aether_blessing_hud_check.gd",
	"res://tests/hotbar_shortcut_check.gd",
	"res://tests/player_hotbar_check.gd",
	"res://tests/player_hotbar_interactive_check.gd",
	"res://tests/legacy_market_cleanup_check.gd",
	"res://tests/wild_battle_experience_reward_check.gd",
	"res://tests/boss_battle_npc_check.gd",
]

const DEFAULT_LOG_DIR := "/tmp/pokeaether_project_checks"

var failed := false
var log_dir := DEFAULT_LOG_DIR


func _init() -> void:
	var configured_log_dir := OS.get_environment("POKEAETHER_TEST_LOG_DIR").strip_edges()
	if not configured_log_dir.is_empty():
		if not configured_log_dir.is_absolute_path():
			push_error("POKEAETHER_TEST_LOG_DIR must be an absolute path.")
			quit(1)
			return
		log_dir = configured_log_dir

	var log_error := DirAccess.make_dir_recursive_absolute(log_dir)
	if log_error != OK:
		push_error("Failed to create check log directory: %s" % log_dir)
		quit(1)
		return

	var executable := OS.get_executable_path()
	var project_path := ProjectSettings.globalize_path("res://")

	print("Running %d project checks..." % CHECK_SCRIPTS.size())
	for script_path in CHECK_SCRIPTS:
		_run_check(executable, project_path, script_path)

	quit(1 if failed else 0)


func _run_check(executable: String, project_path: String, script_path: String) -> void:
	var output: Array = []
	var log_file := "%s/%s.log" % [log_dir, _script_log_name(script_path)]
	var exit_code := OS.execute(
		executable,
		PackedStringArray([
			"--no-header",
			"--headless",
			"--log-file",
			log_file,
			"--path",
			project_path,
			"--script",
			script_path,
		]),
		output,
		true
	)

	if exit_code == 0:
		print("PASS %s" % script_path)
		return

	failed = true
	push_error(
		"FAIL %s exit_code=%d log=%s\n%s" % [script_path, exit_code, log_file, _format_output(output)]
	)


func _format_output(output: Array) -> String:
	var parts: Array[String] = []
	for item in output:
		parts.append(str(item))
	return "\n".join(parts)


func _script_log_name(script_path: String) -> String:
	return script_path.replace("res://", "").replace("/", "_").replace(".", "_")
