extends SceneTree

const Workspace := preload("res://scripts/ui/trade_workspace.gd")
const DraggableWindow := preload("res://scripts/ui/draggable_subwindow.gd")

var failed := false


func _init() -> void:
	var candidates := Workspace.collect_candidates(
		[{"ownedPokemonId":11,"speciesId":"pidgey","level":12}]
	)
	_check(candidates.size() == 1, "only party candidates are collected")
	_check(candidates[0].get("pokemonId", 0) == 11, "party identity preserved")
	_check(candidates[0].get("location", {}).get("type", "") == "party", "party location")
	var workspace := Workspace.new()
	_check(workspace._pokemon_label({"nickname":null, "speciesName":null, "speciesId":"rattata", "level":4}) == "rattata  Lv. 4", "null nickname falls back to species id")
	var rendered_slot := workspace._create_offer_slot()
	workspace.selected_ids.assign([11])
	workspace._render_offer_slot(rendered_slot, {"pokemonId":11,"speciesId":"pidgey","speciesName":"Pidgey","level":12}, true, 0)
	_check(rendered_slot.get_child_count() == 1, "filled offer slot builds its styled content")
	rendered_slot.free()
	_check(Workspace.build_drop_replacement([11], 12, -1, 2) == [11, 12], "drop appends within capacity")
	_check(Workspace.build_drop_replacement([11], 12, 0, 1) == [12], "drop onto occupied slot replaces it")
	_check(Workspace.build_drop_replacement([11], 12, -1, 1) == [11], "drop cannot exceed recipient capacity")
	_check(Workspace.build_drop_replacement([11], 11, 0, 5) == [11], "duplicate drop is harmless")
	_check(Workspace.normalize_summary_payload({"pokemonId":11,"speciesId":"pidgey"}).get("species", "") == "pidgey", "public offer identity opens readonly summary")
	var drag_parent := Window.new()
	drag_parent.size = Vector2i(500, 400)
	root.add_child(drag_parent)
	var drag_window := DraggableWindow.new()
	drag_window.size = Vector2i(120, 80)
	drag_window.position = Vector2i(10, 10)
	drag_parent.add_child(drag_window)
	drag_window.begin_window_drag()
	var drag_motion := InputEventMouseMotion.new()
	drag_motion.relative = Vector2(24, 18)
	drag_window._input(drag_motion)
	_check(drag_window.position == Vector2i(34, 28), "summary host follows relative pointer movement")
	drag_window.end_window_drag()
	drag_window.queue_free()
	drag_parent.queue_free()
	workspace.trade = {"tradeId":"trade-1", "revision":3, "lastEventSeq":4}
	_check(not workspace._trade_snapshot_changed({"tradeId":"trade-1", "revision":3, "lastEventSeq":4}), "identical active snapshot does not refresh candidates")
	_check(workspace._trade_snapshot_changed({"tradeId":"trade-1", "revision":4, "lastEventSeq":5}), "changed active snapshot refreshes candidates")
	_check(Workspace.should_center_for_trade(false, "trade-1", "trade-1"), "initial workspace opening is centered")
	_check(Workspace.should_center_for_trade(true, "trade-1", "trade-2"), "a different trade is centered")
	_check(not Workspace.should_center_for_trade(true, "trade-1", "trade-1"), "updates preserve a dragged workspace position")
	_check(Workspace.trade_window_size_for_viewport(Vector2i(1920, 1080)) == Vector2i(1120, 680), "large viewports use the desired workspace size")
	_check(Workspace.trade_window_size_for_viewport(Vector2i(1024, 600)) == Vector2i(1004, 580), "compact viewports keep the workspace footer on screen")
	_check(Workspace.participant_display_name({"displayName":"Ash Ketchum","username":"ash"}, "Player") == "Ash Ketchum", "trade headings prefer participant display names")
	_check(Workspace.participant_display_name({"username":"misty"}, "Player") == "misty", "trade headings fall back to usernames")
	_check(Workspace.participant_display_name({}, "Other Player") == "Other Player", "trade headings fail closed to a neutral label")
	workspace.free()
	var source := FileAccess.get_file_as_string("res://scripts/ui/trade_workspace.gd")
	_check(not source.contains("Leave Trade"), "workspace has no separate leave button")
	_check(source.contains("close_requested.connect(_on_close_requested)"), "window close owns authoritative trade leave")
	_check(source.contains("mouse_default_cursor_shape = Control.CURSOR_POINTING_HAND"), "trade buttons use the pointing-hand cursor")
	_check(source.contains("borderless = true") and source.contains("close_button.pressed.connect(_on_close_requested)"), "workspace uses custom chrome without changing close semantics")
	_check(source.contains("_on_window_header_gui_input") and source.contains("_clamp_window_position"), "trade workspace header supports bounded dragging")
	_check(source.contains("str(trade.get(\"status\", \"\")) in [\"active\", \"locked\"]"), "only open trades are cancelled by window close")
	_check(source.contains("func _ready() -> void:\n\thide()"), "workspace starts hidden without an active trade")
	_check(source.contains("replace_offer"), "workspace uses complete replacement")
	_check(not source.contains("CheckButton"), "workspace no longer renders toggle candidates")
	_check(not source.contains("Send Offer"), "valid drops immediately replace the authoritative offer")
	_check(source.contains("try_offer_party_drop"), "workspace accepts party-slot drops")
	_check(source.contains("func try_offer_party_drop") and source.contains("if candidates.size() <= 1:"), "workspace validates the final-party-Pokemon rule when an offer is dropped")
	var drag_function := source.get_slice("func begin_party_offer_drag", 1).get_slice("func update_party_offer_drag", 0)
	_check(not drag_function.contains("candidates.size() <= 1"), "the final party Pokemon may still be dragged for consistent interaction feedback")
	_check(source.contains("_main_to_workspace_position"), "drop hit testing converts main viewport coordinates into the trade window")
	_check(source.contains("begin_party_offer_drag") and source.contains("update_party_offer_drag"), "trade window renders its own drag preview")
	_check(source.contains("local_offer_slots") and source.contains("opponent_offer_slots"), "workspace renders two stable offer boxes")
	_check(source.contains("slot.custom_minimum_size = Vector2(82, 86)"), "Pokemon offer slots stay vertically compact")
	_check(source.contains("_render_participant_names"), "offer columns identify both participants")
	_check(source.contains("status_panel.visible = message.strip_edges() != \"\""), "empty status chrome does not waste vertical space")
	_check(source.contains("open_trade_pokemon_summary"), "offered Pokemon open the shared readonly summary")
	_check(not source.contains("name_label.text = _pokemon_name(pokemon)"), "offer slots use the sprite and tooltip instead of cramped Pokemon names")
	_check(not source.contains("hide_for_pokemon_summary"), "opening a summary keeps the trade workspace visible")
	_check(source.contains("_local_offer_nonempty"), "Ready depends only on the local participant offer")
	_check(source.contains("opponent_ready_indicator") and source.contains("_opponent_participant_ready"), "workspace shows authoritative opponent readiness")
	_check(source.contains('"ui.trade.error.offer_required"'), "workspace explains the localized Ready requirement")
	_check(source.contains("func _trade_snapshot_changed"), "candidate refresh is gated by authoritative snapshot changes")
	_check(source.contains("PlayerPartyStateService"), "workspace reuses party service")
	_check(not source.contains("PokemonStorageService"), "PC storage is excluded from trade selection and settlement refresh")
	_check(source.contains("partyCount"), "workspace limits offers by opponent free party slots")
	_check(source.contains('"ui.trade.ready"'), "localized readiness control")
	_check(source.contains('"ui.trade.edit"'), "localized explicit edit control")
	_check(source.contains("lockedReview"), "server locked review rendering")
	_check(source.contains('"ui.trade.review.give"') and source.contains('"ui.trade.review.receive"'), "localized immutable exchange labels")
	_check(source.contains('"ui.trade.confirm"'), "localized locked review confirmation control")
	_check(source.contains("lockedRevision") and source.contains("snapshotHash"), "confirmation references immutable review")
	_check(not source.contains("or not realtime.connected"), "websocket status does not block authoritative trade commands")
	_check(not source.contains("owner_user_id"), "client does not perform ownership settlement")
	var overlay_source := FileAccess.get_file_as_string("res://scripts/ui/ui_overlay.gd")
	_check(overlay_source.contains("_try_offer_party_drag_to_trade"), "party drag delegates offer drops before party reordering")
	_check(overlay_source.contains("party_drag_workspace_preview"), "party drag preview is hosted above the trade window")
	_check(overlay_source.contains("_promote_trade_summary_to_window") and overlay_source.contains("host_parent.add_child(host)"), "trade summaries render as transient children above the workspace")
	_check(overlay_source.contains("host.always_on_top = false"), "summary tooltips may render above their summary host")
	_check(overlay_source.contains("func _trade_workspace_is_visible") and overlay_source.contains("_show_pokemon_summary"), "party summaries use the higher trade window layer while trading")
	_check(overlay_source.contains("DRAGGABLE_SUBWINDOW") and overlay_source.contains("begin_window_drag"), "promoted summary windows use their existing header as a drag handle")
	quit(1 if failed else 0)


func _check(value: bool, label: String) -> void:
	if not value:
		failed = true
		push_error(label)
